[account_keywords]
revenue = [
    "매출액",
    "수익(매출액)",
    "영업수익",
    "매출",
    "영업수익(매출액)",
    "보험료수익",
    "이자수익"
]

operating_profit = [
    "영업이익",
    "영업이익(손실)",
    "영업손익",
    "영업이익 (손실)",
    "영업손실(이익)",
    "조정영업이익",
    "영업손실",
    "영업손익(손실)",
    "영엽손실",
    "영엽이익"
]

net_income = [
    "당기순이익",
    "당기순이익(손실)",
    "당기순손익",
    "당기의 순이익",
    "당기순이익 (손실)",
    "순이익(손실)",
    "순이익",
    "분기순이익",
    "분기순이익(손실)",
    "분기의 순이익",
    "분기연결순이익",
    "분기연결순이익(손실)",
    "반기순이익",
    "반기순이익(손실)",
    "반기의 순이익",
    "반기연결순이익",
    "반기연결순이익(손실)",
    "당(반)기순이익",
    "당(반)기순이익(손실)",
    "연결당기순이익",
    "연결당기순이익(손실)",
    "당기순이익(비지배지분포함)",
    "당기순손실",
    "법인세비용차감전순손실",
    "분기순손익",
    "반기순손익",
    "분기순손실",
    "반기순손실",
    "당기순손실(이익)",
    "지배기업의 소유주지분",
    "지배기업의소유주지분",
    "지배기업 소유주지분",
    "지배주주순이익",
    "지배지분 당기순이익",
    "지배지분당기순이익",
    "지배주주지분순이익",
    "지배주주지분 당기순이익"
]
